# Testing purpose.
version: '3'
services:
  http:
    image: ghcr.io/shinycolorswiki/mediawiki:latest
    build: .
    command: nginx -g 'daemon off;'
    ports:
      - 8080:8080
    volumes:
      - ./dev/nginx.conf:/etc/nginx/http.d/default.conf:ro
      - sitemap:/srv/wiki/sitemap:ro
      - images:/srv/wiki/w/images:ro
  fastcgi:
    image: ghcr.io/shinycolorswiki/mediawiki:latest
    build: .
    volumes:
      - ./dev:/setting:ro
      - sitemap:/srv/wiki/sitemap
      - images:/srv/wiki/w/images
    environment:
      - MEDIAWIKI_SERVER=http://127.0.0.1:8080
      - MEDIAWIKI_DEBUG=1
    depends_on:
      - mariadb
      - redis
      - elasticsearch
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    volumes:
      - db:/config
    environment:
      - MYSQL_ROOT_PASSWORD=therootpassword
      - MYSQL_DATABASE=shinywiki
      - MYSQL_USER=shinywiki
      - MYSQL_PASSWORD=shinywiki
    expose:
      - 3306
  redis:
    image: redis:7-alpine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    

volumes:
  sitemap:
  images:
  db:
  redis: