#!/bin/bash
set -euo pipefail

echo "Starting wiki..."

# PHP Version
_phpv=81

# Wait until other services are fully started.
seconds=10
echo "Wait $seconds(s) for boot other system..."
sleep $seconds

if [ -z "${MEDIAWIKI_SKIP_INSTALL:-}" ]; then
  echo "Start install mediawiki..."
  DB_NAME="$(php -r 'require "/setting/secret.php"; echo $wgDBname;')"
  DB_HOSTNAME="$(php -r 'require "/setting/secret.php"; echo $wgDBserver;')"
  DB_USERNAME="$(php -r 'require "/setting/secret.php"; echo $wgDBuser;')"
  DB_PASSWORD="$(php -r 'require "/setting/secret.php"; echo $wgDBpassword;')"
  php$_phpv /srv/wiki/w/maintenance/install.php \
    --scriptpath '/w' \
    --dbtype mysql \
    --dbname "${DB_NAME}" \
    --dbserver "${DB_HOSTNAME}" \
    --dbuser "${DB_USERNAME}" \
    --dbpass "${DB_PASSWORD}" \
    --installdbuser "${DB_USERNAME}" \
    --installdbpass "${DB_PASSWORD}" \
    --pass 'shinycolors.wiki' \
    'admin' admin
fi

# Overwrite to existing configuration.
ln -sf /setting/wiki/LocalSettings.php /srv/wiki/w/LocalSettings.php
ln -sf /setting/aws.env /etc/aws.env

rebuild_index () {
    # Search Elastic Index
    sudo -u nginx -g www-data php$_phpv /srv/wiki/w/extensions/CirrusSearch/maintenance/UpdateSearchIndexConfig.php --startOver && \
    sudo -u nginx -g www-data php$_phpv /srv/wiki/w/extensions/CirrusSearch/maintenance/ForceSearchIndex.php --skipLinks --indexOnSkip & \
    sudo -u nginx -g www-data php$_phpv /srv/wiki/w/extensions/CirrusSearch/maintenance/ForceSearchIndex.php --skipParse & \
    sudo -u nginx -g www-data php$_phpv /srv/wiki/w/extensions/CirrusSearch/maintenance/ForceSearchIndex.php 

    # SMW Elastic Index
    # sudo -u nginx -g www-data php$_phpv /srv/wiki/w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php
}

if [ -z "${MEDIAWIKI_SKIP_UPDATE:-}" ]; then
    sudo -u nginx -g www-data php$_phpv /srv/wiki/w/maintenance/update.php --quick 
fi

# Update SFS
/bin/bash /usr/local/bin/update-sfs || :

# Start cron daemon
crond -b


###
# PHP Config
###

# Override listen
sed -i -e "s/listen = 127.0.0.1:9000/listen = 0.0.0.0:9000/g" /etc/php$_phpv/php-fpm.d/www.conf

# Override clear_env for pass docker variables
sed -i -e "s/;\?clear_env = \(no\|yes\)/clear_env = no/g" /etc/php$_phpv/php-fpm.d/www.conf

# Override error log for output to docker (stderr)
sed -i -e "s/;\?error_log = \(.\+\)/error_log = \/dev\/stderr\n/g" /etc/php$_phpv/php-fpm.conf

# Override owner/group for proper permission
sed -i -e "s/;\?user = nobody/user = nginx/g" /etc/php$_phpv/php-fpm.d/www.conf
sed -i -e "s/;\?group = nobody/group = www-data/g" /etc/php$_phpv/php-fpm.d/www.conf
sed -i -e "s/;\?listen\.owner = nobody/listen\.owner = nginx/g" /etc/php$_phpv/php-fpm.d/www.conf
sed -i -e "s/;\?listen\.group = nobody/listen\.group = www-data/g" /etc/php$_phpv/php-fpm.d/www.conf

# Override pm value for performance
sed -i -e "s/;\?pm = dynamic/pm = static/g" /etc/php$_phpv/php-fpm.d/www.conf
sed -i -e "s/;\?pm\.max_children = 5/pm\.max_children = 8/g" /etc/php$_phpv/php-fpm.d/www.conf

# Run rebuild index and php-fpm
if [ -z "${MEDIAWIKI_SKIP_REBUILD_INDEX:-}" ]; then
    rebuild_index & /usr/sbin/php-fpm$_phpv -F
else
    /usr/sbin/php-fpm$_phpv -F
fi
