#!/bin/bash

# --------
# Settings
# --------

# PHP Version
_phpv=84

datestamp=`date +'%Y-%m-%d'`
php="sudo -u nginx -g www-data php$_phpv"
wikiname="shinywiki"
tempdir="/tmp/wiki-dumps-$datestamp"
workingdir="/srv/wiki"

## START
echo " START "

day=`date +'%d'`

mkdir $tempdir
chown nginx:www-data $tempdir

# Get AWS Environment...
cat /etc/aws.env | sed 's/^\(.*\)$/export \1/g' | grep -E "^export AWS" | cat - > /etc/aws.env.sh
source /etc/aws.env.sh
rm /etc/aws.env.sh

# --- Generate ---

$php $workingdir/w/maintenance/dumpBackup.php --current --output=bzip2:$tempdir/$wikiname-current-$datestamp.xml.bz2
if [ $day == "01" ] || [ $day == "15" ]
then
    $php $workingdir/w/maintenance/dumpBackup.php --full --output=bzip2:$tempdir/$wikiname-full-$datestamp.xml.bz2
fi

# --- Upload ---

/usr/local/bin/s3-uploader -b $AWS_BUCKET_DUMP -f $tempdir/$wikiname-current-$datestamp.xml.bz2
if [ $day == "01" ] || [ $day == "15" ]
then
    /usr/local/bin/s3-uploader -b $AWS_BUCKET_DUMP -f $tempdir/$wikiname-full-$datestamp.xml.bz2
fi

# --- Cleanup ---

cd /

rm -rf $tempdir

echo " DONE "