#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
# --------
# Settings
# --------

# PHP Version
_phpv=83

datestamp=$(date +%F)
day=$(date +%d)
php_cmd=(sudo -u nginx -g www-data php"${_phpv}")
wikiname="shinywiki"
tempdir="/tmp/wiki-dumps-${datestamp}"
workingdir="/srv/wiki"


maintenance() {
    "${php_cmd[@]}" "$workingdir/w/maintenance/run.php" "$@"
}

## START
echo " BACKUP START "

mkdir -p "$tempdir"
chown nginx:www-data "$tempdir"

# Get AWS Environment...
cat /etc/aws.env | sed 's/^\(.*\)$/export \1/g' | grep -E "^export AWS" | cat - > /etc/aws.env.sh
source /etc/aws.env.sh
rm /etc/aws.env.sh

# --- Generate ---

maintenance dumpBackup \
  --current --output="bzip2:${tempdir}/${wikiname}-current-${datestamp}.xml.bz2"

if [[ "$day" == "01" || "$day" == "15" ]]; then
  maintenance dumpBackup \
    --full --output="bzip2:${tempdir}/${wikiname}-full-${datestamp}.xml.bz2"
fi

# --- Upload ---

/usr/local/bin/s3-uploader -b "$AWS_BUCKET_DUMP" \
  -f "${tempdir}/${wikiname}-current-${datestamp}.xml.bz2"

if [[ "$day" == "01" || "$day" == "15" ]]; then
  /usr/local/bin/s3-uploader -b "$AWS_BUCKET_DUMP" \
    -f "${tempdir}/${wikiname}-full-${datestamp}.xml.bz2"
fi

# --- Cleanup ---

cd /

rm -rf "$tempdir"

echo " BACKUP DONE "