#!/bin/sh

# PHP Version
_phpv=81

cd /srv/wiki

sudo -u nginx -g www-data \
    php$_phpv w/maintenance/generateSitemap.php \
    --memory-limit=50M \
    --fspath=sitemap \
    --identifier=shinywiki \
    --urlpath=/sitemap/ \
    --server=https://shinycolors.wiki \
    --compress=yes
