#!/bin/sh

cd /srv/wiki/w

mkdir /var/log/mw
sudo -u caddy -g www-data php maintenance/runJobs.php --type="enotifNotify" > /var/log/mw/runJobs.log 2>&1
sudo -u caddy -g www-data php maintenance/runJobs.php --type="htmlCacheUpdate" --maxjobs=50 > /var/log/mw/runJobs.log 2>&1
sudo -u caddy -g www-data php maintenance/runJobs.php --wait --maxtime=3600 > /var/log/mw/runJobs.log 2>&1
