#!/bin/sh

# PHP Version
_phpv=83

cd /srv/wiki/w

maintenance() {
    sudo -u nginx -g www-data php$_phpv /srv/wiki/w/maintenance/run.php "$@"
}

mkdir -p /var/log/mw
maintenance runJobs --type="webVideoTranscode" >> /var/log/mw/runJobs.log 2>&1
